name: travelogue_flutter
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #network
  vexana: ^3.5.4

  #database
  shared_preferences: ^2.2.2

  #language
  easy_localization: ^3.0.3

  # utilities
  kartal: ^3.5.0
  equatable: ^2.0.5
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0


flutter:

  assets:
    - assets/animations/
    - assets/icons/


  uses-material-design: true

  
  

  
